### ISSUE TITLE
یک ویژگی ساده

### ISSUE THREAD

**Issue by raaaas** [Mr30nama/30nama#2]
سلام

می شه تنظیمات مثلا ساب تایتل نباشه و کیفیت 1080 باشه را کاری کنید سیو بشه هر سری نزنم ؟

یکی دوباره اولش اوکیه ولی اینکه هر سری بزنی واقعا دیگه روی اعصاب می ره

**Comment by Mr30nama** [comment]
چون سرعت اینترنت پایدار نیست به همین دلیل به صورت خودکار سعی میکنه سیستم بهترین سرعت را انتخاب کنه دوست عزیز

**Comment by raaaas** [comment]
> 
> 
> چون سرعت اینترنت پایدار نیست به همین دلیل به صورت خودکار سعی میکنه سیستم بهترین سرعت را انتخاب کنه دوست عزیز

سرعت اینترنتم که پایداره مشکلی از اون ندارم البته شب شما عملا غیرقابل تماشا هستید حتی با پایین ترین کیفیت برای همین دیگه تمدید هم نکردم . ولی همچنان تنظیمات ساب تایتل فکر نکنم ربطی به اینترنت داشته باشه که نشوند داده بشه یا نه 

شاید هم اشتباه می کنم !
